'use client';
import {useState} from 'react';

type Item={q:string;es:string;ru:string};

const starters:Item[]=[
{q:'Nunca he probado el forshmak. ¿Qué es exactamente?',es:'Es un paté tradicional de arenque con manzana, huevo, mantequilla y patata. Tiene un sabor salado y equilibrado, y lo servimos frío.',ru:'Это традиционный паштет из сельди с яблоком, яйцом, сливочным маслом и картофелем. Вкус солоноватый и сбалансированный, подаётся холодным.'},
{q:'¿El forshmak sabe muchísimo a arenque?',es:'Se nota el arenque, pero no es agresivo. La manzana, el huevo, la mantequilla y la patata suavizan y equilibran el sabor.',ru:'Сельдь чувствуется, но вкус не резкий. Яблоко, яйцо, масло и картофель делают его мягче и сбалансированнее.'},
{q:'¿Por qué decís que el arenque tiene dos texturas?',es:'Porque una parte del arenque está triturada dentro del paté y otra queda en pequeños trozos. Así la textura no es completamente lisa.',ru:'Потому что часть сельди измельчена в паштете, а часть остаётся небольшими кусочками. Поэтому текстура не полностью однородная.'},
{q:'No me gusta mucho el hígado. ¿El paté de pollo tiene un sabor muy fuerte?',es:'No, es bastante suave, fino y cremoso. El sabor del hígado está presente, pero es delicado.',ru:'Нет, он довольно мягкий, нежный и кремовый. Вкус печени чувствуется, но он деликатный.'},
{q:'¿Qué lleva exactamente vuestro paté de hígado de pollo?',es:'Lleva hígado de pollo, cebolla, zanahoria, nata y mantequilla. Queda muy suave y cremoso.',ru:'В нём куриная печень, лук, морковь, сливки и сливочное масло. Текстура получается очень нежной и кремовой.'},
{q:'¿Qué tiene de especial el paté de caballa ahumada?',es:'Lo hacemos con caballa ahumada, nata agria, limón, cebollino, eneldo y un toque de rábano picante. Es ahumado, fresco y equilibrado.',ru:'Мы делаем его из копчёной скумбрии со сметаной, лимоном, шнитт-луком, укропом и лёгкой нотой хрена. Вкус копчёный, свежий и сбалансированный.'},
{q:'¿El paté de caballa es completamente liso como una mousse?',es:'No. Es cremoso, pero conserva fibras de la caballa, así que tiene algo de textura.',ru:'Нет. Он кремовый, но в нём сохраняются волокна скумбрии, поэтому текстура остаётся немного выраженной.'},
{q:'Quiero probar varios sabores, ¿qué me recomiendas para compartir?',es:'Te recomiendo el surtido de tres patés. Incluye hígado de pollo, caballa ahumada y forshmak, y va muy bien para compartir.',ru:'Советую сет из трёх паштетов: куриная печень, копчёная скумбрия и форшмак. Это хороший вариант, чтобы попробовать разные вкусы и поделиться.'},
{q:'¿Qué tres patés vienen en el surtido?',es:'Paté de hígado de pollo, paté de caballa ahumada y forshmak.',ru:'Паштет из куриной печени, паштет из копчёной скумбрии и форшмак.'},
{q:'¿El pan lo hacéis vosotros aquí?',es:'No lo presentamos como pan hecho aquí. Servimos panes de masa madre; normalmente dos de trigo y uno de centeno.',ru:'Мы не говорим, что хлеб печём здесь. Подаём хлеб на закваске: обычно два пшеничных и один ржаной.'},
{q:'¿Esto es una ensaladilla rusa normal?',es:'Es nuestra versión auténtica de Olivje. Lleva pollo, dos tipos de pepino, un corte más grande, menos mayonesa y huevas de trucha.',ru:'Это наша версия настоящего оливье. В нём курица, два вида огурца, более крупная нарезка, меньше майонеза и сверху икра форели.'},
{q:'¿Qué diferencia hay entre vuestro Olivje y una ensaladilla rusa española?',es:'Usamos pollo en lugar de atún, pepino fresco y fermentado, un corte más grande y menos mayonesa. Lo terminamos con huevas de trucha.',ru:'У нас курица вместо тунца, свежий и ферментированный огурец, более крупная нарезка и меньше майонеза. Сверху добавляем икру форели.'},
{q:'¿Qué son esas huevas naranjas que lleva el Olivje por encima?',es:'Son huevas de trucha.',ru:'Это икра форели.'},
{q:'¿Qué es la Shuba? Nunca la he visto.',es:'Es un pastel frío en capas con arenque, verduras, huevo, remolacha y mayonesa. La remolacha le da su color característico.',ru:'Это холодный слоёный салат с сельдью, овощами, яйцом, свёклой и майонезом. Характерный цвет даёт свёкла.'},
{q:'¿La Shuba es como un pastel?',es:'Visualmente sí, porque se monta en capas y se corta como un pastel, pero es una ensalada fría salada con arenque y remolacha.',ru:'Внешне да: она собирается слоями и режется как торт. Но это холодный солёный салат с сельдью и свёклой.'},
{q:'¿Qué significa que la Shuba está hecha en capas?',es:'Que los ingredientes no se mezclan todos juntos: arenque, verduras, huevo y remolacha se colocan en capas sucesivas con mayonesa.',ru:'Ингредиенты не перемешиваются все вместе: сельдь, овощи, яйцо и свёкла укладываются последовательными слоями с майонезом.'},
{q:'¿Los rollitos de berenjena llevan carne?',es:'No. Son rollitos de berenjena con un relleno de nueces, cebolla, cilantro, ajo y khmeli-suneli.',ru:'Нет. Это рулетики из баклажана с начинкой из грецких орехов, лука, кинзы, чеснока и хмели-сунели.'},
{q:'¿Qué lleva el relleno de los rollitos de berenjena?',es:'Nueces, cebolla, cilantro, ajo y khmeli-suneli, una mezcla tradicional de especias georgianas.',ru:'Грецкие орехи, лук, кинза, чеснок и хмели-сунели — традиционная грузинская смесь специй.'},
{q:'Esta ensalada de tomate parece muy sencilla. ¿Qué tiene de especial?',es:'Usamos tres tipos de tomate de temporada, pepino, cebolla dulce y eneldo. Es sencilla, pero el producto y el aliño son lo importante.',ru:'Мы используем три вида сезонных томатов, огурец, сладкий лук и укроп. Салат простой, но здесь важны качество продукта и заправка.'},
{q:'¿Qué aliño me recomiendas para la ensalada de tomates si quiero probarla de la forma más tradicional?',es:'Aceite de girasol aromático. Es el aliño que le da el carácter más tradicional.',ru:'Ароматное подсолнечное масло. Именно оно даёт салату наиболее традиционный характер.'},
{q:'Quiero una ensalada fresca, pero con algo de carácter. ¿Qué me recomiendas?',es:'La ensalada de remolacha y queso de cabra: es fresca, pero tiene contraste entre la remolacha, el queso, los frutos secos y la vinagreta de miel y mostaza.',ru:'Салат со свёклой и козьим сыром: он свежий, но с характером за счёт сочетания свёклы, сыра, орехов и медово-горчичной заправки.'},
{q:'¿Qué lleva exactamente la ensalada de remolacha y queso de cabra?',es:'Hojas verdes, remolacha cocida, queso de cabra, nueces, piñones y una vinagreta de miel y mostaza.',ru:'Зелёные листья, варёная свёкла, козий сыр, грецкие и кедровые орехи и медово-горчичная заправка.'},
{q:'¿Estas setas nameko son champiñones?',es:'No. Son setas nameko, una variedad diferente. Las servimos frías, marinadas con cebolla.',ru:'Нет. Это грибы намеко, другой вид грибов. Мы подаём их холодными, маринованными с луком.'},
{q:'¿Qué es el salo y cómo se sirve?',es:'Es tocino curado. Nosotros lo trituramos con ajo y hierbas y lo servimos sobre pan de centeno.',ru:'Сало — это солёный свиной жир. У нас его измельчают с чесноком и зеленью и подают на ржаном хлебе.'},
{q:'¿El jolodets lleva gelatina añadida?',es:'No. Cuaja de forma natural gracias al caldo muy concentrado de cerdo y pollo.',ru:'Нет. Он застывает естественным образом благодаря концентрированному бульону из свинины и курицы.'},
{q:'El jolodets parece gelatina. ¿Es un plato dulce?',es:'No, es un plato salado y frío, parecido a un áspic de carne. Lo servimos con rábano picante y mostaza.',ru:'Нет, это холодное солёное мясное заливное. Подаём его с хреном и горчицей.'},
{q:'¿Qué es el vinigret? ¿Lleva mayonesa?',es:'Es una ensalada fría de remolacha, patata, zanahoria, chucrut y pepinillo fermentado o salado. No lleva mayonesa; usamos aceite de girasol aromático.',ru:'Это холодный салат из свёклы, картофеля, моркови, квашеной капусты и солёного или ферментированного огурца. Майонеза нет, заправляем ароматным подсолнечным маслом.'},
{q:'¿Qué aportan el chucrut y el pepinillo al vinigret?',es:'Aportan acidez, salinidad y un carácter fermentado que equilibra el dulzor de la remolacha y las verduras cocidas.',ru:'Они добавляют кислотность, солёность и ферментированный характер, балансируя сладость свёклы и варёных овощей.'},
{q:'¿Qué llevan los huevos rellenos con espadines de Riga?',es:'Llevan yema de huevo, salsa tártara y espadines ahumados de Riga. Se sirven fríos sobre pan de centeno.',ru:'В начинке желток, соус тартар и копчёные рижские шпроты. Подаются холодными на ржаном хлебе.'},
{q:'¿Qué lleva la salsa tártara de los huevos rellenos?',es:'Mayonesa, nata agria, alcaparras, cebolla roja y pepinillo encurtido.',ru:'Майонез, сметана, каперсы, красный лук и маринованный огурец.'}
];

const soupsMains:Item[]=[
{q:'Un cliente pregunta: «¿Qué es el borsch?». Explícaselo de forma natural en 20–30 segundos.',es:'Es una sopa tradicional de remolacha sobre caldo de ternera, con col y un toque ahumado de panceta y ciruelas pasas. Nuestra versión no lleva patata y se sirve con nata agria.',ru:'Это традиционный свекольный суп на говяжьем бульоне с капустой и лёгкой копчёной нотой от грудинки и чернослива. В нашей версии нет картофеля, подаём со сметаной.'},
{q:'Un cliente dice: «No me gustan las cremas. ¿El borsch es una crema de remolacha?». Respóndele.',es:'No, no es una crema. Es una sopa sobre caldo de ternera con remolacha, col y carne; tiene textura de sopa tradicional.',ru:'Нет, это не крем-суп. Это суп на говяжьем бульоне со свёклой, капустой и мясом, с обычной суповой текстурой.'},
{q:'Un cliente pregunta: «¿El borsch lleva patata?». Responde y explica brevemente qué lleva nuestra versión.',es:'No, nuestra versión no lleva patata. Lleva caldo de ternera, remolacha, col, panceta ahumada y ciruelas pasas, y se sirve con nata agria.',ru:'Нет, в нашей версии картофеля нет. Есть говяжий бульон, свёкла, капуста, копчёная грудинка и чернослив, подаём со сметаной.'},
{q:'Un cliente dice que le gustan los sabores ahumados. Explícale de dónde viene el toque ahumado de nuestro borsch.',es:'El toque ahumado viene de la panceta ahumada y de las ciruelas pasas ahumadas. Es una nota presente, pero equilibrada con el dulzor y la acidez.',ru:'Копчёная нота идёт от копчёной грудинки и копчёного чернослива. Она заметная, но сбалансирована сладостью и кислотностью.'},
{q:'Un cliente pregunta: «¿Qué diferencia hay entre el borsch y la solyanka?». Compara brevemente el carácter de las dos sopas.',es:'El borsch es de remolacha, más equilibrado entre dulzor, acidez y ahumado. La solyanka es más intensa, cárnica, salada y ácida, con embutidos, pepinos, aceitunas, alcaparras y limón.',ru:'Борщ — свекольный, с балансом сладости, кислотности и копчёности. Солянка более насыщенная, мясная, солёно-кислая, с колбасами, огурцами, оливками, каперсами и лимоном.'},
{q:'Un cliente pregunta: «¿Qué es la solyanka?». Explícasela en español.',es:'Es una sopa de carne muy intensa y reconfortante sobre caldo de ternera, con varios embutidos, pepinos salados, tomate, aceitunas, alcaparras y limón. Se sirve con nata agria.',ru:'Это очень насыщенный мясной суп на говяжьем бульоне с несколькими видами мясных продуктов, солёными огурцами, томатом, оливками, каперсами и лимоном. Подаётся со сметаной.'},
{q:'Un cliente dice: «Entonces la solyanka es simplemente una sopa con salchichas, ¿no?». Respóndele correctamente.',es:'Tiene varios embutidos, pero no es solo eso. Su carácter viene también del caldo de ternera, los pepinos salados, el tomate, las aceitunas, las alcaparras y el limón.',ru:'В ней есть несколько мясных продуктов, но это не просто суп с колбасой. Характер дают также говяжий бульон, солёные огурцы, томат, оливки, каперсы и лимон.'},
{q:'Un cliente quiere una sopa muy intensa y cárnica. Recomiéndale una opción y explica por qué.',es:'Le recomendaría la solyanka. Es nuestra sopa más intensa y cárnica, con caldo de ternera, varios embutidos y una acidez marcada de pepino, alcaparras y limón.',ru:'Я бы рекомендовал солянку. Это самый насыщенный и мясной суп, с говяжьим бульоном, несколькими видами мясных продуктов и выраженной кислотностью огурцов, каперсов и лимона.'},
{q:'Un cliente quiere algo casero, reconocible y reconfortante. Háblale de nuestra sopa de pollo.',es:'La sopa de pollo es muy clásica y casera: caldo de pollo intenso y dorado, fideos de huevo gruesos, huevo cocido y hierbas. Es muy reconfortante.',ru:'Куриный суп очень домашний и понятный: насыщенный золотистый куриный бульон, толстая яичная лапша, варёное яйцо и зелень. Очень уютное блюдо.'},
{q:'Un cliente pregunta: «¿La sopa de pollo es muy ligera, tipo dieta?». Responde sin crear una expectativa incorrecta.',es:'No la describiría como una sopa de dieta. El caldo es intenso y tiene cuerpo, aunque el plato sigue siendo sencillo y casero.',ru:'Я бы не называл её диетическим лёгким супом. Бульон насыщенный и плотный по вкусу, хотя само блюдо остаётся простым и домашним.'},
{q:'Un cliente pregunta qué tipo de fideos lleva la sopa de pollo. Explícalo sin llamarlos fideuà.',es:'Lleva fideos de huevo gruesos, de estilo casero. No son fideuà.',ru:'В супе толстая домашняя яичная лапша. Это не fideuà.'},
{q:'Un cliente español ve el plov y dice: «Ah, es como una paella». Respóndele de forma diplomática.',es:'Se parece en que es un plato de arroz, pero el plov tiene otra técnica, otras especias y otra textura. Lo hacemos con cordero, comino y lo servimos con ensalada achichuk.',ru:'Сходство в том, что это блюдо из риса, но у плова другая техника, специи и текстура. Мы готовим его с бараниной и зирой и подаём с салатом ачичук.'},
{q:'Un cliente pregunta: «¿Qué es el plov?». Explica su composición y carácter.',es:'Es un plato tradicional uzbeko de arroz con cordero, cebolla, zanahoria y comino. Es aromático y sabroso, y se acompaña con achichuk para aportar frescura y acidez.',ru:'Это традиционное узбекское блюдо из риса с бараниной, луком, морковью и зирой. Оно ароматное и насыщенное, а ачичук добавляет свежесть и кислотность.'},
{q:'Un cliente pregunta: «¿Qué es el achichuk y para qué sirve?». Explícaselo.',es:'Es una ensalada fresca de tomate maduro, cebolla marinada y hierbas. Su acidez y frescura equilibran la riqueza del plov.',ru:'Это свежий салат из спелых томатов, маринованного лука и зелени. Его кислотность и свежесть балансируют насыщенность плова.'},
{q:'Un cliente pregunta por qué usamos arroz basmati en un plato uzbeko. Respóndele.',es:'Es una adaptación práctica: aquí no siempre podemos conseguir de forma estable los arroces centroasiáticos adecuados, y el basmati nos da un resultado consistente.',ru:'Это практическая адаптация: подходящие среднеазиатские сорта риса здесь сложно получать стабильно, а басмати даёт предсказуемый результат.'},
{q:'Un cliente quiere pedir Beef Stroganoff. Haz correctamente la toma del pedido, incluyendo la pregunta obligatoria.',es:'Perfecto. Nuestro Stroganoff lleva un steak de ternera cortado sobre salsa cremosa de setas. ¿Qué punto de cocción prefiere para la carne?',ru:'Отлично. Наш строганов — это нарезанный говяжий стейк на сливочно-грибном соусе. Какую степень прожарки мяса вы предпочитаете?'},
{q:'Un cliente pregunta: «¿La carne del Stroganoff viene guisada dentro de la salsa?». Explica nuestra versión.',es:'No. En nuestra versión cocinamos un steak al punto que elija el cliente, lo cortamos y lo servimos sobre la salsa cremosa de setas.',ru:'Нет. В нашей версии мы готовим стейк до выбранной гостем прожарки, нарезаем его и подаём на сливочно-грибном соусе.'},
{q:'Un cliente pide Stroganoff pero no indica el punto de la carne. ¿Qué le preguntas y cómo?',es:'Le preguntaría: «¿Qué punto de cocción prefiere para la carne: poco hecha, al punto o más hecha?»',ru:'Я бы спросил: «Какую прожарку мяса вы предпочитаете: слабую, среднюю или более сильную?»'},
{q:'Un cliente pregunta: «¿Qué es el esturión?». Explica el plato y el origen de nuestro pescado.',es:'El esturión es el pescado del que procede el caviar. El nuestro viene de una piscifactoría local cerca de Valencia y lo cocinamos sous-vide para mantenerlo delicado y jugoso.',ru:'Осётр — это рыба, от которой получают икру. Наш осётр из местного хозяйства недалеко от Валенсии, готовим sous-vide, чтобы сохранить нежность и сочность.'},
{q:'Utiliza la frase «Es la madre del caviar» y después explica correctamente qué significa.',es:'Es la madre del caviar: es decir, es el pescado del que procede el caviar. Aquí servimos el esturión como pescado, cocinado sous-vide.',ru:'Это «мать икры», то есть рыба, от которой получают икру. У нас осётр подаётся как рыба, приготовленная sous-vide.'},
{q:'Un cliente pregunta: «¿El esturión tiene un sabor muy fuerte a pescado?». Respóndele.',es:'No, tiene un sabor bastante delicado y suave. No es un pescado de sabor agresivo.',ru:'Нет, вкус довольно деликатный и мягкий. Это не рыба с резким рыбным вкусом.'},
{q:'Un cliente pregunta cómo se cocina el esturión y con qué se acompaña. Explícaselo.',es:'Lo marinamos con hierbas y lo cocinamos sous-vide. Lo acompañamos con puré, chips de chirivía, guisantes y brócoli.',ru:'Мы маринуем его с травами и готовим sous-vide. Подаём с пюре, чипсами из пастернака, горошком и брокколи.'},
{q:'Un cliente ve FILETE RUSO DE POLLO y pregunta: «¿Es un filete entero de pollo?». Explícalo.',es:'No. Es una kotleta hecha con carne picada de pechuga y muslo de pollo. Queda muy tierna y jugosa.',ru:'Нет. Это котлета из измельчённого мяса куриной грудки и бедра. Она получается очень нежной и сочной.'},
{q:'Explica a un cliente por qué nuestro FILETE RUSO DE POLLO queda tierno y jugoso.',es:'Usamos una mezcla de pechuga y muslo: la pechuga aporta textura y el muslo ayuda a mantener la jugosidad.',ru:'Мы используем смесь грудки и бедра: грудка даёт структуру, а бедро помогает сохранить сочность.'},
{q:'Un cliente pide que le recomiendes uno de los platos calientes más populares de VOLGA. Háblale del FILETE RUSO DE POLLO.',es:'Te recomendaría el Filete Ruso de Pollo, uno de nuestros platos más populares. Es una kotleta muy tierna y jugosa de pechuga y muslo, con puré y pepino ligeramente salado.',ru:'Я бы рекомендовал куриную котлету Filete Ruso — одно из наших самых популярных горячих блюд. Она очень нежная и сочная, из грудки и бедра, с пюре и малосольным огурцом.'},
{q:'Un cliente pregunta: «¿Qué son los draniki?». Explícaselos.',es:'Son tortitas de patata rallada y cebolla, crujientes por fuera y tiernas por dentro.',ru:'Это картофельные оладьи из тёртого картофеля и лука, хрустящие снаружи и нежные внутри.'},
{q:'Un cliente pregunta qué acompañamientos puede elegir con los draniki. Déjale claro que se elige una sola opción.',es:'Puede elegir una de dos opciones: salsa de setas o salmón ligeramente salado. Son alternativas, no se sirven las dos juntas.',ru:'Можно выбрать один из двух вариантов: грибной соус или малосольный лосось. Это альтернативы, вместе они не подаются.'},
{q:'Un cliente quiere «algo crujiente de patata». Recomiéndale los draniki y describe su textura.',es:'Te recomiendo los draniki: son tortitas de patata rallada y cebolla, doradas y crujientes por fuera, pero tiernas por dentro.',ru:'Советую драники: это оладьи из тёртого картофеля и лука, румяные и хрустящие снаружи, но нежные внутри.'},
{q:'Un cliente dice: «No conozco la cocina del Este. Quiero algo bastante familiar». Recomienda un plato de esta sección y explica por qué.',es:'Le recomendaría el Filete Ruso de Pollo: es fácil de entender, muy tierno y jugoso, y se sirve con puré y pepino ligeramente salado. Es una buena entrada a nuestra cocina.',ru:'Я бы рекомендовал куриную котлету Filete Ruso: блюдо понятное, очень нежное и сочное, подаётся с пюре и малосольным огурцом. Хороший вариант для первого знакомства с нашей кухней.'},
{q:'Un cliente duda entre plov, Stroganoff y esturión. Explica brevemente el carácter de cada uno sin limitarte a enumerar ingredientes.',es:'El plov es aromático y contundente, con cordero y comino. El Stroganoff es más cremoso y cárnico, con steak y salsa de setas. El esturión es la opción más delicada y ligera de sabor.',ru:'Плов — ароматный и насыщенный, с бараниной и зирой. Строганов — более сливочный и мясной, со стейком и грибным соусом. Осётр — самый деликатный и мягкий по вкусу вариант.'}
];

const seasonal:Item[]=[
{q:'¿Qué es el kharcho?',es:'Es una sopa georgiana intensa y aromática. En nuestra versión usamos arroz bomba, un guiño cercano para Valencia porque es el arroz que muchos clientes conocen de la paella, aunque el plato y la técnica son completamente distintos.',ru:'Это насыщенный ароматный грузинский суп. В нашей версии используем рис bomba — понятный валенсийскому гостю ориентир, но само блюдо и техника совсем не похожи на паэлью.'},
{q:'¿Entonces el kharcho es como una paella georgiana?',es:'Solo se puede usar la comparación por el arroz bomba. El kharcho es una sopa georgiana con un perfil y una técnica completamente diferentes.',ru:'Сравнение допустимо только как ориентир по рису bomba. Харчо — грузинский суп с совершенно другой техникой и характером.'},
{q:'Quiero una sopa intensa y reconfortante. ¿Qué me recomiendas?',es:'Te recomendaría el kharcho: es profundo, aromático y con bastante carácter, una buena opción si quieres una sopa contundente y diferente.',ru:'Я бы рекомендовал харчо: насыщенный, ароматный, с характером — хороший вариант для гостя, который хочет плотный и необычный суп.'},
{q:'¿La ujá de Carelia es una crema de salmón?',es:'No es una crema triturada. Es una sopa de pescado con salmón, patata, zanahoria, nata y hierbas; resulta redonda, cremosa y reconfortante.',ru:'Это не крем-суп. Это рыбный суп с лососем, картофелем, морковью, сливками и зеленью; вкус округлый, сливочный и уютный.'},
{q:'Quiero una sopa de pescado suave, pero no demasiado ligera.',es:'La ujá de Carelia encaja muy bien: tiene salmón y nata, así que es suave y redonda, pero con suficiente cuerpo para resultar reconfortante.',ru:'Карельская уха хорошо подходит: лосось и сливки дают мягкость и округлость, но суп остаётся достаточно насыщенным.'},
{q:'¿La ujá lleva nata?',es:'Sí. Lleva nata, por eso tiene un carácter más redondo y cremoso. No la presentamos como una sopa ligera ni como una crema triturada.',ru:'Да, в ней есть сливки, поэтому вкус более округлый и кремовый. Не описываем её как очень лёгкий суп и не называем крем-супом.'},
{q:'Vitello tonnato… entonces la salsa lleva atún, ¿verdad?',es:'Nuestra salsa está inspirada en el vitello tonnato, pero no lleva atún. La hacemos con espadines ahumados, mostaza de Dijon y alcaparras.',ru:'Наш соус вдохновлён vitello tonnato, но тунца в нём нет. Основа — копчёные шпроты, дижонская горчица и каперсы.'},
{q:'¿Qué son los espadines ahumados y qué aportan a la salsa?',es:'Son pequeños pescados ahumados. Aportan profundidad, salinidad y una nota ahumada que da personalidad a nuestra salsa.',ru:'Это небольшая копчёная рыба. Она даёт соусу глубину, солёность и копчёную ноту.'},
{q:'Tengo alergia al pescado. ¿Puedo pedir la lengua?',es:'La salsa contiene pescado porque está hecha con espadines ahumados. Antes de confirmar el pedido hay que advertirlo claramente y, si hace falta, consultar cocina sobre una alternativa segura.',ru:'Соус содержит рыбу, потому что сделан на копчёных шпротах. Нужно обязательно предупредить гостя и при необходимости уточнить безопасную альтернативу на кухне.'},
{q:'¿Qué es Garni Yarakh?',es:'Es un plato armenio de berenjena rellena. Para un cliente que no conoce el nombre, lo más útil es empezar por esa descripción sencilla y después explicar su origen.',ru:'Это армянское блюдо из фаршированного баклажана. Незнакомому гостю лучше сначала объяснить понятную форму блюда, а затем происхождение.'},
{q:'¿Garni Yarakh es georgiano?',es:'No, es armenio. Está dentro de la familia de sabores del Cáucaso, pero su origen es armenio.',ru:'Нет, это армянское блюдо. Оно относится к кавказской гастрономической традиции, но происхождение именно армянское.'},
{q:'¿Qué son los kurze?',es:'Son una especialidad de Daguestán parecida en forma a unos ravioli. Los nuestros llevan relleno de cordero y ternera; usamos “ravioli” solo como comparación para que el cliente entienda la idea.',ru:'Это дагестанское блюдо, по форме понятное через сравнение с ravioli. У нас начинка из баранины и говядины; сравнение нужно только как ориентир.'},
{q:'¿Qué carne llevan los kurze y de dónde son?',es:'Son de Daguestán y el relleno lleva cordero y ternera.',ru:'Курзе — дагестанское блюдо, начинка из баранины и говядины.'},
{q:'¿En qué se diferencian de unos ravioli italianos?',es:'La comparación ayuda a entender la forma, pero el plato es daguestaní, con otro relleno, otra tradición y otro carácter. No los presentamos como ravioli italianos.',ru:'Сравнение помогает понять форму, но это дагестанское блюдо с другой начинкой, традицией и характером. Не называем его итальянскими ravioli.'},
{q:'Quiero algo otoñal, suave y elegante.',es:'El muslo de pato sous-vide es una muy buena opción. Tiene una cocción suave, puré de calabaza y una salsa de frutos rojos que aporta contraste y acidez.',ru:'Хороший вариант — утиная ножка sous-vide: мягкое приготовление, тыквенное пюре и ягодный соус, который даёт контраст и кислотность.'},
{q:'¿Por qué cocináis el pato sous-vide y con qué va?',es:'La cocción sous-vide ayuda a conseguir una textura tierna y controlada. Lo acompañamos con puré de calabaza y una salsa de frutos rojos.',ru:'Sous-vide помогает получить мягкую и контролируемую текстуру. Подаём с тыквенным пюре и ягодным соусом.'},
{q:'No suelo pedir caza porque me preocupa que tenga un sabor demasiado fuerte.',es:'El jabalí tiene carácter, pero en nuestro plato se equilibra con cerveza negra, frutos del bosque y trigo sarraceno. Si prefieres sabores muy suaves, te orientaría hacia otra opción.',ru:'У кабана есть характер, но тёмное пиво, лесные ягоды и гречка его балансируют. Если гость любит совсем мягкие вкусы, лучше предложить альтернативу.'},
{q:'¿Con qué va el jabalí?',es:'Lo cocinamos con cerveza negra y lo acompañamos con frutos del bosque y trigo sarraceno. La cerveza aporta profundidad, las bayas acidez y la grechka un carácter muy de otoño.',ru:'Кабан готовится с тёмным пивом, лесными ягодами и гречкой. Пиво даёт глубину, ягоды — кислотность, гречка — выраженный осенний характер.'},
{q:'¿La salsa de las costillas es barbacoa?',es:'No. Usamos un demi-glace elaborado en nuestra cocina. Tiene más profundidad y un perfil más gastronómico que una salsa barbacoa industrial.',ru:'Нет. Используем demi-glace собственного приготовления. Он глубже и гастрономичнее промышленного BBQ-соуса.'},
{q:'Quiero carne contundente, pero no una salsa BBQ típica.',es:'Te recomendaría la costilla de cerdo. La servimos con demi-glace hecho en nuestra cocina y patatas baby, así que mantiene un perfil reconocible pero más profundo.',ru:'Я бы рекомендовал свиное ребро: домашний demi-glace и baby-картофель дают понятное, но более глубокое и гастрономичное блюдо.'},
{q:'¿El rollito de col lleva arroz, como uno tradicional?',es:'No lleva arroz. El relleno es de salmón y dorada, envuelto en col, y lo servimos con salsa de fumet. Por eso resulta más ligero que un rollito tradicional de carne.',ru:'Риса нет. Начинка — лосось и дорадо, завёрнутые в капусту, подача с соусом фуме. Поэтому блюдо легче традиционного мясного голубца.'},
{q:'¿La salsa del rollito de pescado es bisque?',es:'La salsa es fumet. Tiene un sabor intenso y una textura que puede recordar a un bisque, pero es más ligera; usamos esa comparación solo para explicar el carácter.',ru:'Соус — fumet. Он насыщенный и по текстуре может напоминать bisque, но легче; сравнение используем только для объяснения характера.'},
{q:'Quiero algo de pescado más ligero que un rollito de col de carne.',es:'El rollito de salmón y dorada encaja muy bien: no lleva arroz, el relleno es de pescado y lo servimos con fumet, así que resulta más ligero.',ru:'Рыбный голубец подходит хорошо: без риса, с лососем и дорадо, под соусом fumet — поэтому он легче мясного варианта.'},
{q:'¿Qué tipo de arroz lleva el risotto de patata?',es:'No lleva arroz. Cortamos y trabajamos la patata para conseguir una sensación parecida a un risotto; justamente ahí está la idea del plato.',ru:'Риса в блюде нет. Картофель нарезают и готовят так, чтобы получить ощущение ризотто — в этом и идея блюда.'},
{q:'Quiero setas y algo original, pero no quiero arroz.',es:'Te recomendaría el risotto de patata con setas. No lleva arroz: la patata se trabaja para crear esa textura de risotto.',ru:'Рекомендую картофельное ризотто с грибами. Риса нет — нужная текстура создаётся за счёт обработки картофеля.'},
{q:'¿Cómo puede ser risotto si no lleva arroz?',es:'Usamos la idea y la textura del risotto, pero el ingrediente principal es la patata. La cortamos y cocinamos para que libere almidón y tenga una textura cremosa similar.',ru:'Берём идею и текстуру ризотто, но основной продукт — картофель. Его режут и готовят так, чтобы крахмал дал похожую кремовую текстуру.'},
{q:'No quiero un postre demasiado dulce.',es:'El rollo de merengue puede funcionar muy bien porque el espino amarillo aporta una acidez marcada que equilibra el dulzor del merengue y la crema.',ru:'Меренговый рулет может подойти: выраженная кислотность облепихи балансирует сладость меренги и крема.'},
{q:'¿Qué aporta el espino amarillo al postre y cómo es la textura?',es:'Aporta una acidez fresca y muy característica. La textura combina un merengue aireado con una crema suave y cremosa.',ru:'Облепиха даёт свежую характерную кислотность. Текстура сочетает воздушную меренгу и мягкий крем.'},
{q:'Tengo alergia al huevo o a los lácteos. ¿Puedo tomar el rollo de merengue?',es:'No es una opción adecuada sin verificar una alternativa: el merengue lleva huevo y la crema contiene lácteos. Hay que informar claramente al cliente.',ru:'Без проверки альтернативы этот десерт не подходит: меренга содержит яйцо, крем — молочные продукты. Гостя нужно предупредить прямо.'},
{q:'Quiero algo muy de otoño, pero no sé si carne, pescado o vegetal.',es:'Primero preguntaría si prefieres carne, pescado o una opción sin carne y si buscas algo intenso o más ligero. Con eso puedo orientarte entre jabalí o costilla, rollito de pescado, pato o risotto de patata.',ru:'Сначала уточняем: мясо, рыба или вариант без мяса, и насколько насыщенный вкус хочет гость. После этого уже выбираем между кабаном/рёбрами, рыбным голубцом, уткой или картофельным ризотто.'}
];

export default function CheatSheet(){
 const[topic,setTopic]=useState<'starters'|'soups_mains'|'seasonal'>('starters');
 const items=topic==='starters'?starters:topic==='soups_mains'?soupsMains:seasonal;
 return <div>
   <div className="sectionTabs" style={{marginBottom:16}}>
     <button className={`sectionTab ${topic==='starters'?'selected':''}`} onClick={()=>setTopic('starters')}>ЗАКУСКИ</button>
     <button className={`sectionTab ${topic==='soups_mains'?'selected':''}`} onClick={()=>setTopic('soups_mains')}>СУПЫ И ГОРЯЧЕЕ</button>
     <button className={`sectionTab ${topic==='seasonal'?'selected':''}`} onClick={()=>setTopic('seasonal')}>ОСЕНЬ ФАНТАЗИЙ</button>
   </div>
   <div className="card">
     <span className="sectionEyebrow">ШПАРГАЛКА К УСТНОЙ ЧАСТИ</span>
     <h2>{topic==='starters'?'Закуски':topic==='soups_mains'?'Супы и горячее':'Осень фантазий'}</h2>
     <p>Это примеры хороших ответов, а не текст для заучивания. На экзамене отвечай естественно и своими словами.</p>
   </div>
   {items.map((x,i)=><details className="card" key={i} style={{marginBottom:12}}>
     <summary style={{cursor:'pointer',fontWeight:700}}>Ситуация {i+1}: {x.q}</summary>
     <div style={{marginTop:14}}>
       <p><b>ES · Пример ответа</b></p>
       <p>{x.es}</p>
       <p><b>RU · Смысл ответа</b></p>
       <p>{x.ru}</p>
     </div>
   </details>)}
 </div>
}
